name: UCTB
channels:
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.15.0=pyhd3eb1b0_0
  - astor=0.8.1
  - blas=1.0=mkl
  - c-ares=1.18.1
  - ca-certificates
  - certifi
  - cffi=1.14.6
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - dataclasses=0.8=pyh4f3eec9_6
  - freetype=2.12.1
  - gast=0.5.3=pyhd3eb1b0_0
  - grpcio=1.31.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - importlib-metadata=4.8.1
  - intel-openmp=2022.1.0
  - keras=2.2.4=0
  - keras-applications=1.0.8=py_1
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - lcms2=2.12
  - lerc=3.0
  - lz4-c=1.9.4
  - markdown=3.3.4
  - mkl=2020.2=256
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - mock=4.0.3=pyhd3eb1b0_0
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.19
  - numpy-base=1.19
  - olefile=0.46=py36_0
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - pillow=8.3.1
  - pip=21.2.2
  - protobuf=3.17.2
  - pycparser=2.21=pyhd3eb1b0_0
  - python=3.6.13
  - pyyaml=5.4.1
  - setuptools=58.0.4
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0=py_0
  - tensorflow-gpu=1.13.1
  - termcolor=1.1.0
  - tk=8.6.12
  - typing_extensions=4.1.1=pyh06a4308_0
  - werkzeug=2.0.3
  - wheel=0.37.1
  - xz=5.2.10
  - yaml=0.2.5
  - zipp=3.6.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pytorch=1.1.0
  - torchvision=0.3.0
  - pip:
    - backports-zoneinfo==0.2.1
    - charset-normalizer==2.0.12
    - chinese-calendar==1.8.0
    - chinesecalendar==1.8.0
    - convertdate==2.3.2
    - cycler==0.11.0
    - decorator==4.4.2
    - gputil==1.4.0
    - hmmlearn==0.2.8
    - importlib-resources==5.4.0
    - joblib==1.1.1
    - kiwisolver==1.3.1
    - lunardate==0.2.0
    - matplotlib==3.3.0
    - mxnet-cu100==1.5.0
    - networkx==2.5.1
    - packaging==21.3
    - pandas==1.1.5
    - patsy==0.5.3
    - pyluach==1.4.2
    - pymeeus==0.5.12
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - scikit-learn==0.24.2
    - smart-open==6.3.0
    - statsmodels==0.12.2
    - tensorboardx==2.6
    - threadpoolctl==3.1.0
    - wget==3.2
    - workalendar==16.4.0
    - xgboost==1.5.2
    - nni==2.6.1
    - UCTB==0.3.5